<a href="https://colab.research.google.com/github/d1keyyy/Project-Altriks-Kelompok-1/blob/main/Basic_Tensor_Arithmetic_(The_Hadamard_Product).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

No.1

In [ ]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
import numpy as np
X = np.array([[25, 2, 3], [5, 26, 7]])

In [ ]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
import torch
X_pt = torch.tensor([[25, 2, 3], [5, 26, 7]])

In [ ]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
import tensorflow as tf
X_tf = tf.Variable([[25, 2, 3], [5, 26, 7]])

In [ ]:
# lakukan perkalian matrix X dengan suatu skalar
X*5

array([[125,  10,  15],
       [ 25, 130,  35]])

In [ ]:
# lakukan penjumlahan matrix X dengan suatu skalar
X+5

array([[30,  7,  8],
       [10, 31, 12]])

In [ ]:
# lakukan pengurangan matrix X dengan suatu skalar
X-5

array([[20, -3, -2],
       [ 0, 21,  2]])

In [ ]:
# lakukan perkalian matrix X_pt dengan suatu skalar
X_pt*5

tensor([[125,  10,  15],
        [ 25, 130,  35]])

In [ ]:
# lakukan penjumlahan matrix X_pt dengan suatu skalar
X_pt+5

tensor([[30,  7,  8],
        [10, 31, 12]])

In [ ]:
# lakukan pengurangan matrix X_pt dengan suatu skalar
X_pt-5

tensor([[20, -3, -2],
        [ 0, 21,  2]])

In [ ]:
# lakukan perkalian matrix X_tf dengan suatu skalar
X_tf*5

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[125,  10,  15],
       [ 25, 130,  35]], dtype=int32)>

In [ ]:
# lakukan penjumlahan matrix X_tf dengan suatu skalar
X_tf+5

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30,  7,  8],
       [10, 31, 12]], dtype=int32)>

In [ ]:
# lakukan pengurangan matrix X_tf dengan suatu skalar
X_tf-5

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[20, -3, -2],
       [ 0, 21,  2]], dtype=int32)>

No.2

In [ ]:
# buat matrix Y dengan ukuran 2x3 menggunakan numpy
import numpy as np
Y = np.array([[3, 2, 25], [7, 26, 5]])

In [ ]:
# buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch
import torch
Y_pt = torch.tensor([[3, 2, 25], [7, 26, 5]])

In [ ]:
# buat matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow
import tensorflow as tf
Y_tf = tf.Variable([[3, 2, 25], [7, 26, 5]])

In [ ]:
# kalikan matrix X dengan Y
X*Y

array([[ 75,   4,  75],
       [ 35, 676,  35]])

In [ ]:
# kalikan matrix X_pt dengan Y_pt
X_pt*Y_pt

tensor([[ 75,   4,  75],
        [ 35, 676,  35]])

In [ ]:
# kalikan matrix X_tf dengan Y_tf
X_tf*Y_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 75,   4,  75],
       [ 35, 676,  35]], dtype=int32)>