In [4]:
import numpy as np
import tensorflow as tf
import torch

### SOAL NOMOR 1

In [5]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[12, 24,78], [33, 22, 90]])
X

array([[12, 24, 78],
       [33, 22, 90]])

In [6]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor ([[12, 24,78], [33, 22, 90]])
X_pt

tensor([[12, 24, 78],
        [33, 22, 90]])

In [7]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.constant([[12, 24,78], [33, 22, 90]])
X_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[12, 24, 78],
       [33, 22, 90]], dtype=int32)>

### SOAL NOMOR 2

In [8]:
# hitung hasil penjumlahan seluruh elemen matrix X
X.sum()

np.int64(259)

In [9]:
# hitung hasil penjumlahan seluruh elemen matrix X_pt
X_pt.sum()

tensor(259)

In [10]:
# hitung hasil penjumlahan seluruh elemen matrix X_tf
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=259>

### SOAL NOMOR 3

In [11]:
# hitung hasil penjumlahan matrix X berdasarkan row nya
X.sum(axis=1)

array([114, 145])

In [12]:
# hitung hasil penjumlahan matrix X_pt berdasarkan row nya
X_pt.sum(axis=1)

tensor([114, 145])

In [13]:
# hitung hasil penjumlahan matrix X_tf berdasarkan row nya
tf.reduce_sum(X_tf, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([114, 145], dtype=int32)>

### SOAL NOMOR 4

In [14]:
# hitung hasil penjumlahan matrix X berdasarkan kolom nya
X.sum(axis=0)

array([ 45,  46, 168])

In [15]:
# hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya
X_pt.sum(axis=0)

tensor([ 45,  46, 168])

In [16]:
# hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya
tf.reduce_sum(X_tf, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 45,  46, 168], dtype=int32)>

### SOAL NOMOR 5

In [17]:
# hitung nilai minimal dari matrix X, X_pt dan X_tf
X.min()

np.int64(12)

In [18]:
# hitung nilai maksimal dari matrix X, X_pt dan X_tf
X.max()

np.int64(90)

In [19]:
# hitung nilai rata-rata dari matrix X, X_pt dan X_tf
X.mean()

np.float64(43.166666666666664)

### SOAL NOMOR 6



In [20]:
# hitung hasil perkalian seluruh elemen matrix X
X.prod()

np.int64(1467797760)

In [21]:
# hitung hasil perkalian seluruh elemen matrix X_pt
X_pt.prod()

tensor(1467797760)

In [22]:
# hitung hasil perkalian seluruh elemen matrix X_tf
tf.reduce_prod(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=1467797760>