<a href="https://colab.research.google.com/github/d1keyyy/Project-Altriks-Kelompok-1/blob/main/Basis%2C_Orthogonal%2C_and_Orthonomal_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### SOAL NOMOR 1

In [ ]:
import numpy as np

In [ ]:
# buat vector i dengan elemen (1,0) dan vector j dengan elemen (0,1)
I = np.array ([1,0])
I

array([1, 0])

In [ ]:
J = np.array ([0,1])
J

array([0, 1])

In [ ]:
# buktikan bahwa vector i dan vector j itu orthogonal
np.dot (I, J)

np.int64(0)

### SOAL NOMOR 2

In [ ]:
# Bagaimana dengan v=(1,2) dan w=(2,-1), apakah juga orthogonal?
V = np.array ([2, 1])
V

array([2, 1])

In [ ]:
W = np.array ([2, -1])
W

array([ 2, -1])

In [ ]:
np.dot (V, W)
# V dan W bukanlah vektor yang orthogonal

np.int64(3)