<a href="https://colab.research.google.com/github/d1keyyy/Project-Altriks-Kelompok-1/blob/main/Matrix_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### SOAL NOMOR 1



In [ ]:
import numpy as np

In [ ]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array ([[19,21], [67,69], [420,41]])
X

array([[ 19,  21],
       [ 67,  69],
       [420,  41]])

In [ ]:
# tampilkan ukuran dari matrix X
X.size

6

In [ ]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[0,:]

array([19, 21])

In [ ]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[:,1]

array([21, 69, 41])

### SOAL NOMOR 2

In [ ]:
import torch
import tensorflow as tf

In [ ]:
# ulangi soal nomor 1 menggunakan pytorch
X_torch = torch.tensor([[19,21], [67,69], [420,41]])
X_torch

tensor([[ 19,  21],
        [ 67,  69],
        [420,  41]])

In [ ]:
X_torch.size()

torch.Size([3, 2])

In [ ]:
X_torch[0,:]

tensor([19, 21])

In [ ]:
X_torch[:,1]

tensor([21, 69, 41])

In [ ]:
# ulangi soal nomor 1 menggunakan tensorflow
X_tf = tf.constant([[19,21], [67,69], [420,41]])
X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 19,  21],
       [ 67,  69],
       [420,  41]], dtype=int32)>

In [ ]:
X_tf.shape

TensorShape([3, 2])

In [ ]:
X_tf[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([19, 21], dtype=int32)>

In [ ]:
X_tf[:,1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([21, 69, 41], dtype=int32)>