<a href="https://colab.research.google.com/github/d1keyyy/Project-Altriks-Kelompok-1/blob/main/Matrix_Multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
import torch

### SOAL NOMOR 1

In [16]:
# buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy
A = np.array([[2,4,1,],[3,5,7]])
b = np.array([[1],[2],[3]])

In [17]:
# buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytorch
A_pt = torch.tensor([[2,4,1],[3,5,7]])
b_pt = torch.tensor([[1],[2],[3]])

In [18]:
# buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow
A_tf = tf.constant([[2,4,1],[3,5,7]])
b_tf = tf.constant([[1],[2],[3]])

### SOAL NOMOR 2

In [19]:
# tampilkan ukuran matrix A dan vector b
print("Ukuran matrix A:", A.shape)
print("Ukuran vector b:", b.shape)

Ukuran matrix A: (2, 3)
Ukuran vector b: (3, 1)


### SOAL NOMOR 3

In [20]:
# kalikan matrix A dengan vector b
np.dot(A,b)

array([[13],
       [34]])

In [21]:
# kalikan matrix A_pt dengan vector b_pt
torch.matmul(A_pt,b_pt)

tensor([[13],
        [34]])

In [22]:
# kalikan matrix A_tf dengan vector b_tf
tf.matmul(A_tf,b_tf)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[13],
       [34]], dtype=int32)>

### SOAL NOMOR 4

In [23]:
# buat matrix B dengan ukuran 3x3 menggunakan numpy
B = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
# buat matrix B_pt dengan ukuran 3x3 menggunakan pytorch
B_pt = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
# buat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow
B_tf = tf.constant([[1,2,3],[4,5,6],[7,8,9]])

### SOAL NOMOR 5

In [26]:
# kalikan matrix A dengan matrix B
np.dot(A,B)

array([[ 25,  32,  39],
       [ 72,  87, 102]])

In [27]:
# kalikan matrix A_pt dengan matrix B_pt
torch.matmul(A_pt,B_pt)

tensor([[ 25,  32,  39],
        [ 72,  87, 102]])

In [28]:
# kalikan matrix A_tf dengan matrix B_tf
tf.matmul(A_tf,B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 25,  32,  39],
       [ 72,  87, 102]], dtype=int32)>

### SOAL NOMOR 6

In [33]:
# buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?
try:
    result_AB = np.dot(A, B)
    result_BA = np.dot(B, A)
    if result_AB.shape == result_BA.shape:
        is_commutative = np.array_equal(result_AB, result_BA)
        print(f"Apakah A * B == B * A? {is_commutative}")
    else:
        print("A * B != B * A karena dimensinya berbeda.")
except ValueError as e:
    print(f"Perkalian matriks A * B == B * A tidak dapat dilakukan atau dibandingkan: {e}")
    print("Ini berarti perkalian tidak bersifat komutatif untuk matriks-matriks ini.")

Perkalian matriks A * B == B * A tidak dapat dilakukan atau dibandingkan: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)
Ini berarti perkalian tidak bersifat komutatif untuk matriks-matriks ini.
