<a href="https://colab.research.google.com/github/d1keyyy/Project-Altriks-Kelompok-1/blob/main/Norms_and_Unit_Vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### SOAL NOMOR 1

In [ ]:
import numpy as np

In [ ]:
# buat vector x dengan ukuran 3x1
X = np.array([[1],
             [2],
             [3]])
X

array([[1],
       [2],
       [3]])

In [ ]:
# hitung nilai L2 norm dari vector x
(1**2 + 2**2 + 3**2)**(1/2)
np.linalg.norm(X)

np.float64(3.7416573867739413)

### SOAL NOMOR 2

In [ ]:
# buat vector v dengan elemen (3,4)
V = np.array ([3, 4])
V

array([3, 4])

In [ ]:
# hitung nilai L2 norm dari vector v
(3**2 + 4**2)**(1/2)
V_norm = np.linalg.norm(V)
V_norm

np.float64(5.0)

In [ ]:
# tampilkan unit vector dari vector v
unit_V = V / V_norm
unit_V

array([0.6, 0.8])

In [ ]:
# hitung panjang unit vector dari vector v
np.linalg.norm(unit_V)

np.float64(1.0)