<a href="https://colab.research.google.com/github/d1keyyy/Project-Altriks-Kelompok-1/blob/main/tensor_transposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

tensor transposition

No.1

In [ ]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
import numpy as np
X = np.array([[25, 2, 7], [5, 26, 3]])
X

array([[25,  2,  7],
       [ 5, 26,  3]])

In [ ]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
import torch
X_pt = torch.tensor([[25, 2, 3], [5, 26, 7]])
X_pt

tensor([[25,  2,  3],
        [ 5, 26,  7]])

In [ ]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
import tensorflow as tf
X_tf = tf.Variable([[25, 2, 3], [5, 26, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25,  2,  3],
       [ 5, 26,  7]], dtype=int32)>

No.2

In [ ]:
# lakukan transpose pada matrix X
X.T

array([[25,  5],
       [ 2, 26],
       [ 7,  3]])

In [ ]:
# lakukan transpose pada matrix X_pt
X_pt.T

tensor([[25,  5],
        [ 2, 26],
        [ 3,  7]])

In [ ]:
# lakukan transpose pada matrix X_tf
tf.transpose(X_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[25,  5],
       [ 2, 26],
       [ 3,  7]], dtype=int32)>