<a href="https://colab.research.google.com/github/d1keyyy/Project-Altriks-Kelompok-1/blob/main/Vectors_and_Vector_Transposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### SOAL NOMOR 1

In [ ]:
import numpy as np

In [ ]:
# buat vector x dengan ukuran 3x1
X = np.array([[67],[69],[21]])
X

array([[67],
       [69],
       [21]])

In [ ]:
# hitung panjang vector x
len(X)

3

In [ ]:
# tampilkan ukuran vector x
X.shape

(3, 1)

In [ ]:
# tampilkan tipe data dari vector x
type(X)

numpy.ndarray

In [ ]:
# akses elemen pertama dari vector x
X[0]

array([67])

In [ ]:
# tampilkan tipe data elemen pertama dari vector x
type(X[0])

numpy.ndarray

### SOAL NOMOR 2

In [ ]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
X_t = X.T
X_t

array([[67, 69, 21]])

In [ ]:
# tampilkan ukuran dari vector x_t
len(X_t)

1

In [ ]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
Y = np.array ([55, 7, 4])
Y_t = Y.T
Y_t

array([55,  7,  4])

In [ ]:
# tampilkan ukuran dari vector y_t
len(Y_t)

3

### SOAL NOMOR 3

In [ ]:
import tensorflow as tf
import torch

In [ ]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
X_tf = tf.transpose(X)
X_tf

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[67, 69, 21]])>

In [ ]:
X_tf.shape

TensorShape([1, 3])

In [ ]:
Y_tf = tf.transpose(Y)
Y_tf

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([55,  7,  4])>

In [ ]:
Y_tf.shape

TensorShape([3])

In [ ]:
X_pt = torch.transpose(torch.from_numpy(X), 0, 1)
X_pt

tensor([[67, 69, 21]])

In [ ]:
X_pt.shape

torch.Size([1, 3])

In [ ]:
Y_pt = torch.transpose(torch.from_numpy(Y.reshape(1, -1)), 0, 1)
Y_pt

tensor([[55],
        [ 7],
        [ 4]])

In [ ]:
Y_pt.shape

torch.Size([3, 1])