### SOAL NOMOR 1



In [5]:
import numpy as np

In [6]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array ([[19,21,67],[69,420,41]])
X

array([[ 19,  21,  67],
       [ 69, 420,  41]])

In [7]:
# tampilkan ukuran dari matrix X
X.size

6

In [8]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[0,:]

array([19, 21, 67])

In [9]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[:,1]

array([ 21, 420])

### SOAL NOMOR 2

In [10]:
import torch
import tensorflow as tf

In [11]:
# ulangi soal nomor 1 menggunakan pytorch
X_torch = torch.tensor([[19,21,67],[69,420,41]])
X_torch

tensor([[ 19,  21,  67],
        [ 69, 420,  41]])

In [12]:
X_torch.size()

torch.Size([2, 3])

In [13]:
X_torch[0,:]

tensor([19, 21, 67])

In [14]:
X_torch[:,1]

tensor([ 21, 420])

In [15]:
# ulangi soal nomor 1 menggunakan tensorflow
X_tf = tf.constant([[19,21,67],[69,420,41]])
X_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 19,  21,  67],
       [ 69, 420,  41]], dtype=int32)>

In [16]:
X_tf.shape

TensorShape([2, 3])

In [17]:
X_tf[0,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([19, 21, 67], dtype=int32)>

In [18]:
X_tf[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 21, 420], dtype=int32)>