<a href="https://colab.research.google.com/github/d1keyyy/Project-Altriks-Kelompok-1/blob/main/Frobenius_Norm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#Frobenius Norm numpy
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

fro_norm = np.linalg.norm(A, 'fro')

print("Matriks A:\n", A)
print("Frobenius Norm:", fro_norm)

Matriks A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Frobenius Norm: 16.881943016134134


In [8]:
#Frobenius Norm pytorch
import torch

A = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.],
                  [7., 8., 9.]])

fro_norm = torch.norm(A, p='fro')

print("Matriks A:\n", A)
print("Frobenius Norm:", fro_norm.item())

Matriks A:
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Frobenius Norm: 16.881942749023438


In [12]:
#Frobenius Norm tensorflow
import tensorflow as tf

A = tf.constant([[1., 2., 3.],
                 [4., 5., 6.],
                 [7., 8., 9.]])

fro_norm = tf.norm(A, ord='euclidean')

print("Matriks A:\n", A.numpy())
print("Frobenius Norm:", fro_norm.numpy())

Matriks A:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Frobenius Norm: 16.881943
