<a href="https://colab.research.google.com/github/d1keyyy/Project-Altriks-Kelompok-1/blob/main/Symmetric_and_Identity_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

### SOAL NOMOR 1

In [2]:
# 1. buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris

A = np.array([
    [1, 2, 3],
    [2, 4, 5],
    [3, 5, 6]
])

A_transpose = A.T

if np.array_equal(A, A.T):
    print("\nA adalah matriks simetris, karena A = A^T")
else:
    print("\nA bukan matriks simetris")


A adalah matriks simetris, karena A = A^T


### SOAL NOMOR 2

In [3]:
# menggunakan pytorch, buatlah matriks identitas I dengan ukuran 4x4
I = torch.eye(4)
I

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [4]:
# menggunakan pytorch, buatlah vector b_pt dengan ukuran 4x1
b_pt = torch.rand(4, 1)
b_pt

tensor([[0.4593],
        [0.6452],
        [0.4235],
        [0.7503]])

In [5]:
# kalikan matrix I dengan vector b_pt
hasil = torch.matmul(I, b_pt)
hasil

tensor([[0.4593],
        [0.6452],
        [0.4235],
        [0.7503]])